[package]
name = "interpreter2"
version = "0.1.0"
edition = "2024"

[dependencies]
map-macro = "0.3.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
